# Number of worker processes to spawn.
# Set to 0 to run everything in a single process without clustering.
# Use 'ncpu' to run as many workers as there are CPU units
num_workers: 0

# Log error messages and gracefully restart a worker if v8 reports that it
# uses more heap (note: not RSS) than this many mb.
worker_heap_limit_mb: 250

# Logger info
logging:
  level: trace
#  streams:
#  # Use gelf-stream -> logstash
#  - type: gelf
#    host: logstash1003.eqiad.wmnet
#    port: 12201

# Statsd metrics reporter
metrics:
  #type: info
  #host: localhost
  #port: 8125

services:
  - name: kartotherian
    # a relative path or the name of an npm package, if different from name
    module: /opt/kartotherian/node_modules/kartotherian/app.js
    # optionally, a version constraint of the npm package
    # version: ^0.4.0
    # per-service config
    conf:
      port: 6533
      # interface: localhost # uncomment to only listen on localhost
      # more per-service config settings
      # the location of the spec, defaults to spec.yaml if not specified
      spec: ./spec.template.yaml
      # allow cross-domain requests to the API (default '*')
      cors: '*'
      # to disable use:
      # cors: false
      # to restrict to a particular domain, use:
      # cors: restricted.domain.org
      # content for the CSP headers
      csp: false  # uncomment this line to disable sending them
      # URL of the outbound proxy to use (complete with protocol)
      # proxy: http://my.proxy.org:8080
      # the list of domains for which not to use the proxy defined above
      # no_proxy_list:
      #   - domain1.com
      #   - domain2.org
      # the list of incoming request headers that can be logged; if left empty,
      # the following headers are allowed: cache-control, content-length,
      # content-type, if-match, user-agent, x-request-id
      # log_header_whitelist:
      #   - cache-control
      #   - content-length
      #   - content-type
      #   - if-match
      #   - user-agent
      #   - x-request-id
      # Uncomment to restrict connections to localhost only
      # interface: localhost
      # Uncomment to disable the X-Powered-By header
      # expose_version: false

      # Kartotherian variables and sources
      variables:
        OPENMAPTILES_V3_TILES_URLS:
        - http://localhost:6533/openmaptiles_v3/{z}/{x}/{y}.pbf
        - http://127.0.0.1:6533/openmaptiles_v3/{z}/{x}/{y}.pbf
        - http://[::1]:6533/openmaptiles_v3/{z}/{x}/{y}.pbf
        OPENMAPTILES_V3_TILES_URLS_INTERNAL:
        - http://kartotherian:6533/openmaptiles_v3_raster/{z}/{x}/{y}.pbf
        BASIC_TILES_URLS:
        - http://localhost:6533/basic/{z}/{x}/{y}.png
        - http://127.0.0.1:6533/basic/{z}/{x}/{y}.png
        - http://[::1]:6533/basic/{z}/{x}/{y}.png
      sources: sources.yaml

      modules:
      - "tilelive-tmstyle"
      - "@kartotherian/overzoom"
      - "@kartotherian/substantial"
      - "@kartotherian/tilelive-tmsource"
      - "@mapbox/tilejson"
      - kartotherian_cache # Local cache
      - "kartotherian_cache/RedisStore" # Redis cache Storage
      - kartotherian_gl # Render raster tiles

      requestHandlers:
      - kartotherian_gl_style_server # Serve Mapbox GL Style
      - kartotherian_sources_list_server # Serve the list of sources
      - "kartotherian_cache/expire" # Cache expiration Endpoint

      sources_server:
        prefix_public: http://localhost:6533 # External hostname, should be changed to https://example.com

      styles:
        prefix_public: http://localhost:6533 # External hostname, should be changed to https://example.com
        prefix_internal: http://kartotherian:6533 # Internal, required for render raster
        paths:
          styles: /styles # Path to styles, in the Docker container
          fonts: /fonts # Path to fonts, in the Docker container
        font_fallback: Klokantech Noto Sans Regular # Serve this font when the font is not found
        styles:
          basic: # Name of the style
            style: klokantech-basic-gl-style/style-local.json # Relative path the style JSON
            sources_map: # Map of the style source (`mbtiles://{v3}`) to source name from `sources.yaml`
              v3: openmaptiles_v3
            sources_map_internal: # Internal, required for render raster
              v3: openmaptiles_v3_raster
          bright: # Name of the style
            style: osm-bright-gl-style/style-local.json # Relative path the style JSON
            sources_map: # Map of the style source (`mbtiles://{v3}`) to source name from `sources.yaml`
              v3: openmaptiles_v3
            sources_map_internal: # Internal, required for render raster
              v3: openmaptiles_v3_raster
